#!/bin/bash

set -e

GIT_REPO_DIR=$(git rev-parse --show-toplevel)
IMAGE_NAME=$(echo $(basename ${GIT_REPO_DIR})-tools)

modified_files=$(git status --porcelain)
if [[ -z "$modified_files" ]]; then
  echo "Repository is clean"
else
  echo -e "Repository has uncommitted changes:\n $modified_files"
  exit 1
fi


# Build the image.
podman build tools -t ${IMAGE_NAME}

# Mount the git repo to /srv, and run the publish script for each of our repos.
for repo in apt-tools-prod yum-tools-prod; do
    echo "Generating HTML listings for '$repo'..."
    podman run --rm -it -v $GIT_REPO_DIR:/srv:Z -w /srv/$repo ${IMAGE_NAME} \
        ./tools/publish-inner dangerzone "$@"
    echo "Successfully generated HTML listings for '$repo'"
done

if [[ -z "$CI" ]]; then
    git add .
    git commit -m "Updating repository metadata"
    echo -e "\nCommit created. Changes ready to be signed!"
fi
